services:
  db:
    image: postgres:15
    container_name: budgeting_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend-api
    container_name: backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend-api/.env
    depends_on:
      - db
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3002:80"
    volumes:
    - ./frontend:/app         # mount local code into container
    - /app/node_modules       # keep container's node_modules separate
    command: npm run dev        # run frontend in dev mode (with hot reload)
    depends_on:
      - backend
    

volumes:
  db_data:
